kodoyoon/SunlightMarket

src/main/java/com/raincloud/sunlightmarket/global/entity/UserRoleEnum.java
src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsImpl.java

UserDetailsImpl.java , UserRoleEnum.java 구현했습니다

feat: UserDetailsImpl.java , UserRoleEnum.java 구현

---

src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthenticationFilter.java
src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthentizationFilter.java
src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsServiceImpl.java

feat: security 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/global/config/RestTemplateConfig.java
src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthenticationFilter.java
src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsImpl.java
src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsServiceImpl.java
src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
src/main/java/com/raincloud/sunlightmarket/user/dto/KakaoUserInfoDto.java
src/main/java/com/raincloud/sunlightmarket/user/dto/request/SingUpRequestDto.java
src/main/java/com/raincloud/sunlightmarket/user/dto/response/SignUpResponseDto.java
src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
src/main/java/com/raincloud/sunlightmarket/user/repository/UserRepository.java
src/main/java/com/raincloud/sunlightmarket/user/service/KakaoService.java
src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java

user 도메인 각 기능 추가
global 도메인 config 부분 카카오 로그인 기능 관련 추가
확인 부탁드릴게요 :)

Feat : User, Kakao 로그인 및 회원가입 구현

---

src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
src/main/java/com/raincloud/sunlightmarket/global/cookie/AuthController.java
src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthorizationFilter.java
src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java

hotfix: 수정

---

src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
src/main/java/com/raincloud/sunlightmarket/item/dto/ItemAllResponseDto.java
src/main/java/com/raincloud/sunlightmarket/item/dto/ItemResponseDto.java

Refactor: CommonResponse상속 대신 제너릭으로 개선

Refactor: CommonResponse상속 대신 제너릭으로 개선

---

src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
src/main/java/com/raincloud/sunlightmarket/item/dto/ItemRequestDto.java
src/main/java/com/raincloud/sunlightmarket/item/dto/ItemResponseDto.java
src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java

Feat: Item Create Authorization 정보 추가 구현

Feat: Item Create Authorization 정보 추가 구현

---

src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
src/main/java/com/raincloud/sunlightmarket/user/dto/request/ProfileRequestDto.java
src/main/java/com/raincloud/sunlightmarket/user/dto/response/ProfileResponseDto.java
src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java

Feat : User 프로필 수정 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/user/entity/Buyer.java
src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java
src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
src/main/java/com/raincloud/sunlightmarket/user/repository/BuyerRepository.java
src/main/java/com/raincloud/sunlightmarket/user/repository/SellerRepository.java
src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java

feat: Buyer&Seller Entity 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
src/main/java/com/raincloud/sunlightmarket/user/dto/request/MyProfileRequestDto.java
src/main/java/com/raincloud/sunlightmarket/user/dto/response/MyProfileResponseDto.java
src/main/java/com/raincloud/sunlightmarket/user/dto/response/UserProfileResponseDto.java
src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java
src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java

Feat : User 내 프로필 조회 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java

Feat: Item과 Order 연결

---

src/main/java/com/raincloud/sunlightmarket/review/toseller/controller/ReviewToSellerController.java
src/main/java/com/raincloud/sunlightmarket/review/toseller/dto/response/UpdateReviewToSellerResponseDto.java
src/main/java/com/raincloud/sunlightmarket/review/toseller/entity/ReviewToSeller.java
src/main/java/com/raincloud/sunlightmarket/review/toseller/service/ReviewToSellerService.java

feat: Review To Seller 리뷰 수정,삭제 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/dto/OrderRequestDto.java
src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
src/main/java/com/raincloud/sunlightmarket/user/entity/Buyer.java
src/main/java/com/raincloud/sunlightmarket/user/repository/BuyerRepository.java

Feat: Order Create 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/dto/OrderRequestDto.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat: 아이템을 올린 유저는 구매 요청을 할 수 없게 함

Feat: 아이템을 올린 유저는 구매 요청을 할 수 없게 함

---

src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java

Refactor: Join된 Column으로 Entity조회할 때 따로 Repository에 함수를 안 거치도록 수정

Refactor: Join된 Column으로 Entity조회할 때 따로 Repository에 함수를 안 거치도록 수정

---

src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java
src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Refactor: 모든 Error메시지들이 Response로 리턴되는 기능 구현

Refactor: 모든 Error메시지들이 Response로 리턴되는 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/review/toseller/controller/ReviewToSellerController.java
src/main/java/com/raincloud/sunlightmarket/review/toseller/entity/ReviewToSeller.java
src/main/java/com/raincloud/sunlightmarket/review/toseller/service/ReviewToSellerService.java
src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java

feat: Review To Seller 좋아요 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat : Orders Read기능 구현

---

src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat : Order Update 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/global/dto/DoubleResponse.java
src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/dto/PublicOrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat : Order 조회 시 Item 작성자여야만 orderId와 address까지 보이게 함
item 작성자가 아니면 orderId를 볼 필요가 없고 address는 민감한 개인정보니까 아무나 볼 수 없도록 함

Feat : Order 조회 시 Item 작성자여야만 orderId와 address까지 보이게 함

---

src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
src/main/java/com/raincloud/sunlightmarket/user/dto/request/PasswordRequestDto.java
src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java

실수로 카카오로그인 브랜치로 올렸습니다...
충돌되는 부분이 없어 괜찮을 것 같지만...확인 부탁드리겠습니다.

Feat : User 비밀번호 수정 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/like/controller/LikeController.java
src/main/java/com/raincloud/sunlightmarket/like/dto/LikeDTO.java
src/main/java/com/raincloud/sunlightmarket/like/entity/Like.java
src/main/java/com/raincloud/sunlightmarket/like/repository/LikeRepository.java
src/main/java/com/raincloud/sunlightmarket/like/service/LikeService.java

Chore : 좋아요 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat : Order Confirm 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Feat : 내 Order들 조회 기능 구현

---

src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/dto/PublicOrderResponseDto.java
src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
src/main/java/com/raincloud/sunlightmarket/order/entity/OrderStatus.java
src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java

Refactor: OrderStatus Enum 만듦
